# Generated by Django 4.2.11 on 2024-03-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCreator',
            fields=[
                ('url_name', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedditQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_name', models.TextField()),
                ('url_id', models.TextField()),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('content_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='query_compendium.contentcreator')),
            ],
        ),
    ]
