# Generated by Django 4.2.11 on 2024-03-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_compendium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditquery',
            name='id',
        ),
        migrations.AddField(
            model_name='redditquery',
            name='url_id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
