# Generated by Django 4.2.11 on 2024-03-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_compendium', '0002_remove_redditquery_id_redditquery_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditquery',
            name='url_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
